# Learn more about configuring your Shopify app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "laravel-shopify-app"
client_id = ""
application_url = "https://shopify-app-template.test"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://shopify-app-template.test/auth/shopify/callback"
]

[webhooks]
api_version = "2024-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = ""
include_config_on_deploy = true
